Repository CS2113-AY1819S1-W12-3/main, pull requests merged in 2018-11, with the labels that each got.

#141 Clear address book when it is encrypted
  docs/team/lws803.adoc
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
Labels: type.enhancement

#157 Refined and clarified find/ search feature
  docs/UserGuide.adoc
  docs/team/lws803.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.enhancement

#158 Beefed up Developer guide and changed some of the implementations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Limminghong.adoc
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/logic/commands/RestoreSnapshotsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RestoreCommandParser.java
  src/main/java/seedu/address/model/backup/BackupList.java
  src/main/java/seedu/address/storage/CsvReader.java
  src/main/java/seedu/address/storage/CsvWriter.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreSnapshotsCommandTest.java
Labels: type.enhancement

#172 Changed my documents to lowercase
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/CSV_Format.png
  docs/images/backupSequenceDiagramLogic.png
  docs/images/backupSequenceDiagramStorage.png
  docs/images/limminghong.png
  docs/team/limminghong.adoc
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/CsvReader.java
Labels: type.task

#174 Refined search feature to include hamming distance for phone and KPI
  docs/UserGuide.adoc
  docs/images/find_results1.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/HammingDistanceUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/ClosestMatchList.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: type.epic

#175 Beefed up user guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/closestMatchList_seq.png
  docs/images/findFeature_seq.png
  docs/images/find_feature1.png
  docs/images/find_results1.png
  docs/images/passwordCommand_seq.png
  docs/images/safe.png
  docs/team/lws803.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.story

#177 Updated tests and Documentation
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/model/person/Kpi.java
  src/main/java/seedu/address/model/person/Note.java
  src/test/java/seedu/address/model/person/KpiTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/PositionTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.task

#184 Text prediction v1.4 rev3
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteArgumentsParser.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteParser.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteParserPair.java
  src/main/java/seedu/address/model/autocomplete/CommandCompleter.java
  src/main/java/seedu/address/model/autocomplete/TextPrediction.java
  src/main/java/seedu/address/model/trie/Trie.java
  src/main/java/seedu/address/model/trie/TrieNode.java
  src/test/java/seedu/address/model/autocomplete/AutoCompleteArgumentsParserTest.java
  src/test/java/seedu/address/model/autocomplete/AutoCompleteParserPairTest.java
  src/test/java/seedu/address/model/autocomplete/AutoCompleteParserTest.java
  src/test/java/seedu/address/model/autocomplete/CommandCompleterTest.java
  src/test/java/seedu/address/model/trie/TrieTest.java
Labels: priority.medium, type.enhancement

#183 The big merge
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/backupSequenceDiagramLogic.png
  docs/images/exportSequenceDiagramLogic.png
  docs/images/exportSequenceDiagramStorage.png
  docs/images/importSequenceDiagramLogic.png
  docs/images/restoreSequenceDiagramLogic.png
  docs/images/restoreSequenceDiagramStorage.png
  docs/images/restoreSnapshotsSequenceDiagramLogic.png
  docs/team/limminghong.adoc
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/logic/commands/RestoreSnapshotsCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/data/RestoreTestXml/1540743391606.xml
  src/test/java/seedu/address/logic/commands/BackUpCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreCommandTest.java
  src/test/java/seedu/address/logic/commands/RestoreSnapshotsCommandTest.java
Labels: priority.high

#180 Trimming down UGDG
  docs/UserGuide.adoc
  docs/team/lws803.adoc
Labels: type.story

#187 Updated DG(schedule)
  docs/DeveloperGuide.adoc
  docs/images/scheduleAddSequenceDiagramStorage.png
  docs/images/scheduleEditSequenceDiagramLogic.png
  docs/images/scheduleEditSequenceDiagramStorage.png
  src/main/java/seedu/address/model/schedule/Schedule.java
Labels: type.task

#190 Edited user guide
  docs/UserGuide.adoc
Labels: type.story

#194 Update docs/DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: type.story

#195 Edited developer guide to include manual testing
  docs/DeveloperGuide.adoc
Labels: type.story

#196 Documentations v1.4 rev1
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/predictText_sequence.png
Labels: priority.high

#197 Added test cases
  docs/DeveloperGuide.adoc
  src/test/java/seedu/address/logic/commands/BackUpCommandTest.java
Labels: priority.high

#199 Slight changes to documentations
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lekoook.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: type.task

#200 Change RepoSense link
  docs/team/lekoook.adoc
  docs/team/lws803.adoc
Labels: type.task
