Repository CS2113-AY1819S1-W12-3/main, pull requests merged in 2018-10, with the labels that each got.

#60 Final touch up for v1.1 milestone
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/peiying.jpeg
Labels: enhancement

#68 List filtering v1.2
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: enhancement

#69 Text prediction v1.2 rev1
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteArgumentsParser.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteParser.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteParserPair.java
  src/main/java/seedu/address/model/autocomplete/CommandCompleter.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/trie/Trie.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: bug, enhancement

#72 Added exception for when password is non alpha numeric
  src/main/java/seedu/address/commons/util/FileEncryptor.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
Labels: enhancement

#75 Remove leading whitespace in text prediction input
  src/main/java/seedu/address/model/autocomplete/AutoCompleteParserPair.java
Labels: enhancement

#76 Text prediction v1.2 rev3
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/autocomplete/CommandCompleter.java
  src/main/java/seedu/address/model/autocomplete/TextPrediction.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#77 Extra fields for find command
  Cheatsheets/Coupling_cohesion.md
  Cheatsheets/Testing.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ClosestMatchList.java
  src/main/java/seedu/address/model/person/NoteContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PositionContainsKeywordsPredicate.java
Labels: enhancement

#79 Updated Note object. Added Edit All function. Added UniqueTagList to store existing tags and associated persons
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/tag/TagNotFoundException.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, status.ongoing

#90 Added find by tag
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ClosestMatchList.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.enhancement

#86 Export and Import implementation
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/RestoreCommandParser.java
  src/main/java/seedu/address/storage/XmlConverter.java
  src/main/resources/view/style.xsl
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: priority.high, type.enhancement, type.epic

#83 Mailto v1.2 rev1
  src/main/java/seedu/address/logic/commands/MailCommand.java
Labels: priority.medium, type.enhancement

#96 Re implementation of import and export feature
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/storage/CsvWriter.java
  src/main/java/seedu/address/storage/XmlConverter.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.high, type.enhancement, type.epic

#107 Improve select command
  src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, type.enhancement

#103 Created a schedule/ToDo list for the AddressBook
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ScheduleAddCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleEditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/schedule/Activity.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagNotFoundException.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedActivity.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SchedulePanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SchedulePanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.high, type.enhancement

#111 Updated Trie to check for unique tags and update tagTrie.
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/autocomplete/CommandCompleter.java
  src/main/java/seedu/address/model/autocomplete/TextPrediction.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.medium, type.bug

#112 Added JUnit tests for Activity and Schedule
  src/main/java/seedu/address/model/schedule/Activity.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/test/java/seedu/address/model/schedule/ActivityTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/testutil/TypicalActivity.java
Labels: priority.medium, type.task

#114 Updated AddCommandParserTest to include additional attributes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Position.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.task

#115 Added JUnit tests to Schedule
  src/main/java/seedu/address/logic/commands/ScheduleAddCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleEditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalActivity.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.task

#116 Added more variety of test cases
  src/main/java/seedu/address/logic/parser/PasswordCommandParser.java
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PasswordCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/KpiContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NotesContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: status.ongoing

#118 Updated Browser and Schedule UI.
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/SchedulePanel.java
  src/main/resources/images/avatar.png
  src/main/resources/images/edit.png
  src/main/resources/images/envelope.png
  src/main/resources/images/house.png
  src/main/resources/images/phone-call.png
  src/main/resources/images/tag.png
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/ScheduleItems.fxml
  src/main/resources/view/SchedulePanel.fxml
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: type.epic

#120 updated colour scheme of application. Updated User Guide
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/schedule/Activity.java
  src/main/java/seedu/address/storage/XmlAdaptedActivity.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/SchedulePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/storage/XmlAdaptedActivityTest.java
Labels: type.task

#117 Beefing up user guide and developer guide
  Collate-TUI.jar
  collated/functional/Limminghong.md
  collated/functional/LowGinWee.md
  collated/functional/lekoook.md
  collated/functional/lws803.md
  collated/test/Limminghong.md
  collated/test/LowGinWee.md
  collated/test/lekoook.md
  collated/test/lws803.md
  collated/unused/lws803-unused.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/lws803.adoc
  unused/HammingDistanceUtil.java
Labels: type.story

#124 Updated UG to include schedule
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/resources/images/address_book_32 - Copy.png
  src/main/resources/images/address_book_32.png
  src/main/resources/images/attempt_at_logo.psd
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.task

#122 Updating UGDG for find and password features
  collated/functional/LowGinWee.md
  collated/functional/lekoook.md
  collated/functional/lws803.md
  collated/test/lekoook.md
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: priority.low, type.story

#125 Update UGDG and README
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.task

#127 Updated Schedule in UG
  docs/UserGuide.adoc
Labels: type.task

#129 Updated User Guide and Developer Guide for milestone V1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CSV_Format.PNG
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/storage/CsvWriter.java
Labels: type.story, type.task

#130 Updated UI and fixed schedule parser
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/ScheduleAddCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleEditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ScheduleAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleEditCommandParser.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/attempt_at_logo.psd
  src/main/resources/view/BrowserPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ScheduleAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/testutil/ActivityBuilder.java
Labels: type.story, type.task

#131 Text prediction v1.4 rev1
  README.adoc
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/PasswordCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/autocomplete/AutoCompleteArgumentsParser.java
  src/main/java/seedu/address/model/autocomplete/CommandCompleter.java
  src/main/java/seedu/address/model/autocomplete/TextPrediction.java
  src/main/java/seedu/address/model/trie/Trie.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/autocomplete/CommandCompleterTest.java
  src/test/java/seedu/address/model/trie/TrieTest.java
Labels: type.enhancement, type.story

#73 Sorting feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: status.ongoing

#134 Mail v1.4 rev1
  src/main/java/seedu/address/logic/commands/MailCommand.java
  src/test/java/seedu/address/logic/commands/MailCommandTest.java
Labels: type.enhancement
